[package] 
name = "wookong-solo-rust" 
version = "0.0.1" 
authors = ["Chester Lee<chester@extropies.com>"] 

[dependencies] 
libc = "0.2.55"
libloading = "0.5.0"
rustc-serialize = "0.3.24"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"